package: redaxo_custom_components
version: '0.0.1'
author: Benjamin Hacker
supportpage: https://github.com/BenJ1337/redaxo_custom_components

requires:
  php:
    version: '>=8.0.0'
  redaxo: '>=5.0.0'
  packages:
    redaxo_input_components: '>=0.0.1'
    redaxo_bootstrap: '>=0.0.1'
    structure: '>=0.0.1'
